create extension if not exists pgcrypto;

create table if not exists site (
  id uuid primary key,
  code varchar(32) not null unique,
  name varchar(128) not null,
  is_active boolean not null default true,
  last_sync_completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists asset (
  id uuid primary key,
  serial_number varchar(96) not null unique,
  container_id varchar(96),
  registered_site_id uuid not null references site(id),
  created_at timestamptz not null default now()
);

create table if not exists transfer_order (
  id uuid primary key,
  asset_id uuid not null references asset(id),
  origin_site_id uuid not null references site(id),
  destination_site_id uuid not null references site(id),
  status varchar(24) not null,
  initiated_by varchar(96) not null,
  initiated_at timestamptz not null,
  completed_at timestamptz,
  completion_note text,
  created_at timestamptz not null default now()
);

create table if not exists sync_batch (
  id uuid primary key,
  site_id uuid not null references site(id),
  status varchar(24) not null,
  started_at timestamptz not null,
  completed_at timestamptz,
  queued_event_count integer not null default 0,
  accepted_event_count integer not null default 0,
  rejected_event_count integer not null default 0,
  replay_result_summary text,
  created_at timestamptz not null default now()
);

create table if not exists event_log (
  id uuid primary key,
  sequence_number bigint generated by default as identity,
  event_type varchar(64) not null,
  asset_id uuid,
  site_id uuid not null references site(id),
  transfer_order_id uuid,
  sync_batch_id uuid,
  source_site_event_id varchar(128),
  occurred_at timestamptz not null,
  ingested_at timestamptz not null default now(),
  payload jsonb not null,
  constraint event_log_site_source_event_unq unique (site_id, source_site_event_id)
);

create table if not exists asset_projection (
  asset_id uuid primary key references asset(id),
  serial_number varchar(96) not null,
  current_site_id uuid references site(id),
  container_id varchar(96),
  status varchar(32) not null,
  last_event_type varchar(64) not null,
  last_event_at timestamptz not null,
  last_sequence bigint not null,
  version integer not null,
  updated_at timestamptz not null default now()
);

create table if not exists inspection (
  id uuid primary key,
  asset_id uuid not null references asset(id),
  site_id uuid not null references site(id),
  status varchar(24) not null,
  notes text not null,
  inspected_at timestamptz not null,
  created_event_id uuid not null references event_log(id)
);

create table if not exists evidence_metadata (
  id uuid primary key,
  inspection_id uuid not null references inspection(id),
  mime_type varchar(96) not null,
  sha256 varchar(128) not null,
  storage_ref varchar(256) not null,
  recorded_at timestamptz not null default now()
);

create table if not exists alert (
  id uuid primary key,
  rule_code varchar(128) not null,
  severity varchar(16) not null,
  status varchar(16) not null default 'open',
  asset_id uuid references asset(id),
  site_id uuid references site(id),
  summary text not null,
  details jsonb not null,
  detected_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists reconciliation_case (
  id uuid primary key,
  alert_id uuid references alert(id),
  asset_id uuid references asset(id),
  site_id uuid references site(id),
  status varchar(24) not null default 'open',
  title varchar(160) not null,
  description text not null,
  opened_by varchar(96) not null,
  opened_at timestamptz not null default now(),
  resolved_by varchar(96),
  resolved_at timestamptz,
  resolution_summary text
);

create index if not exists idx_event_log_asset_sequence on event_log(asset_id, sequence_number);
create index if not exists idx_event_log_site_occurred_at on event_log(site_id, occurred_at);
create index if not exists idx_event_log_transfer_order_id on event_log(transfer_order_id);
create index if not exists idx_event_log_sync_batch_id on event_log(sync_batch_id);
create index if not exists idx_transfer_order_status on transfer_order(status);
create index if not exists idx_alert_status_detected_at on alert(status, detected_at desc);
create index if not exists idx_reconciliation_case_status_opened_at on reconciliation_case(status, opened_at desc);
